	.align 2
voicegroup194:: @ 86B429C
	@ piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ acoustic / grand piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ bright acoustic piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric grand piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ honkey-tonk piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ harpsichord
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ clavinet
	@ chromatic percussion
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ celesta
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ glockenspiel
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ music box
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ vibraphone
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ marimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ xylophone
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ tubular bells
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dulcimer
	@ organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ drawbar organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ percussive organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ rock organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ church organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ reed organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ accordion
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ harmonica
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ bandoneon
	@ guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ acoustic guitar (nylon)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ acoustic guitar (steel)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric guitar (jazz)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric guitar (clean)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric guitar (muted)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric guitar (overdrive)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric guitar (distorted)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electrig guitar (harmonics)
	@ bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ acoustic bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric bass (finger)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric bass (picked)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ electric bass (fretless)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ slap bass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ slap bass 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth bass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth bass 2
	@ strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ violin
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ viola
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ cello
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ contrabass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ tremolo strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pizzicato strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ orchestral harp
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ timpani
	@ ensamble
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ string ensamble 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ string ensamble 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth strings 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth strings 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ choir aahs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ voice oohs (or Doohs)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth voice
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ orchestral hit
	@ brass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ trombone
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ tuba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ muted trumpet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ french horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ brass section
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth brass 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth brass 2
	@ reed
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ soprano sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ alto sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ tenor sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ baritone sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ oboe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ english horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ bassoon
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ clarinet
	@ pipe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ piccolo
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ recorder
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pan flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ blown bottle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ shakuhachi
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ whistle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ ocarina
	@ synth lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 5
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 6
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 7
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ lead 8
	@ synth pad
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 5
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 6
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 7
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ pad 8
	@ synth effects
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 5
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 6
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 7
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ FX 8
	@ ethnic
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ sitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ banjo
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ shamisen
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ koto
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ kalimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ bag pipe
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ fiddle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ shanai
	@ percussive
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ tinkle bell
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ cowbell
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ steel drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ woodblock
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ taiko drum
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ melodic tom
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ synth drum
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ reverce cymball
	@ sound effects
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ guitar fret
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ breath
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ seashore
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ bird tweet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ telephone ring
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ helicopter
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ applause
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ gunshot
