[General]
ApplicationVersion = '''0.4.1.2'''
FreeSpaceSearch = '''000200'''
FreeSpaceBuffer = '''100'''
NextExportID = '''0'''

#################################
[[NamedAnchors]]
Name = '''data.header.title'''
Address = 0x0000A0
Format = '''`asc`12'''

[[NamedAnchors]]
Name = '''data.header.gamecode'''
Address = 0x0000AC
Format = '''`asc`4'''

[[NamedAnchors]]
Name = '''data.header.makercode'''
Address = 0x0000B0
Format = '''`asc`2'''

[[NamedAnchors]]
Name = '''data.header.romname'''
Address = 0x000108
Format = '''`asc`32'''

[[NamedAnchors]]
Name = '''data.pokemon.names'''
Address = 0x3237A8
Format = '''[name""11]412'''

[[NamedAnchors]]
Name = '''data.pokemon.moves.names'''
Address = 0x32495C
Format = '''^[name""13]355'''

[[NamedAnchors]]
Name = '''data.abilities.names'''
Address = 0x3268BB
Format = '''[name""13]78'''

[[NamedAnchors]]
Name = '''data.trainers.classes.names'''
Address = 0x2EFF50
Format = '''[name""13]1'''

[[NamedAnchors]]
Name = '''data.pokemon.type.names'''
Address = 0x927A4A
Format = '''^[name""7]data.pokemon.type.length'''

[[NamedAnchors]]
Name = '''data.items.stats'''
Address = 0x57AC40
Format = '''[name""14 index: price: holdeffect.holdeffects param. description<""> keyitemvalue. bagkeyitem. pocket. type. fieldeffect<> battleusage:: battleeffect<> battleextra::]377'''

[[NamedAnchors]]
Name = '''data.abilities.descriptions'''
Address = 0x326CB4
Format = '''[description<"">]data.abilities.names'''

[[NamedAnchors]]
Name = '''graphics.pokemon.sprites.front'''
Address = 0x31536C
Format = '''[sprite<`lzs4x8x8`> uncompressedLength: index:]data.pokemon.names+28'''

[[NamedAnchors]]
Name = '''graphics.pokemon.sprites.back'''
Address = 0x30DA98
Format = '''[sprite<`lzs4x8x8`> uncompressedLength: index:]data.pokemon.names+28'''

[[NamedAnchors]]
Name = '''graphics.pokemon.palettes.normal'''
Address = 0x30E858
Format = '''[palette<`lzp4`> index: unused:]data.pokemon.names+28'''

[[NamedAnchors]]
Name = '''graphics.pokemon.palettes.shiny'''
Address = 0x30F618
Format = '''[palette<`lzp4`> index: unused:]data.pokemon.names+28'''

[[NamedAnchors]]
Name = '''graphics.pokemon.icons.sprites'''
Address = 0x572F48
Format = '''[icon<`ucs4x4x8|graphics.pokemon.icons.index`>]data.pokemon.names+28'''

[[NamedAnchors]]
Name = '''graphics.pokemon.icons.index'''
Address = 0x573628
Format = '''[index.graphics.pokemon.icons.palettes]data.pokemon.names+28'''

[[NamedAnchors]]
Name = '''graphics.pokemon.icons.palettes'''
Address = 0x5737E0
Format = '''[palette<`ucp4`> id::]3'''

[[NamedAnchors]]
Name = '''graphics.items.ball.sprites'''
Address = 0x3375EC
Format = '''[sprite<`lzs4x2x6|graphics.items.ball.palettes`> uncompressedLength: a b]12'''

[[NamedAnchors]]
Name = '''graphics.items.ball.palettes'''
Address = 0x33764C
Format = '''[palette<`lzp4`> a b unused:]graphics.items.ball.sprites'''

[[NamedAnchors]]
Name = '''data.pokemon.stats'''
Address = 0x32B5B8
Format = '''[hp. attack. def. speed. spatk. spdef. type1.data.pokemon.type.names type2.data.pokemon.type.names catchRate. baseExp. evs:|t|hp:|atk:|def:|spd:|spatk:|spdef: item1:data.items.stats item2:data.items.stats genderratio. steps2hatch. basehappiness. growthrate. egg1.egggroups egg2.egggroups ability1.data.abilities.names ability2.data.abilities.names runrate. unknown. padding:]data.pokemon.names'''

[[NamedAnchors]]
Name = '''data.items.berry.stats'''
Address = 0x5E4AF4
Format = '''[name""7 firmness. size: maxYield. minYield. description1<""> description2<""> stageDuration. spicy. dry. sweet. bitter. sour. smoothness:]43'''

[[NamedAnchors]]
Name = '''data.pokemon.moves.stats.battle'''
Address = 0x327A84
Format = '''[effect.moveeffectoptions power. type.data.pokemon.type.names accuracy. pp. effectAccuracy. target|b[]movetarget priority. info|b[]moveinfo unused. unused:]data.pokemon.moves.names'''

[[NamedAnchors]]
Name = '''data.decorations.stats'''
Address = 0x59CEF4
Format = '''[id. name""16 permission.decorpermissions shape.decorshape category.decorcategory price:: description<""> graphics<>]121'''

[[NamedAnchors]]
Name = '''scripts.moves.effects'''
Address = 0x326EF0
Format = '''[effect<`bse`>]moveeffectoptions'''

[[NamedAnchors]]
Name = '''graphics.townmap.icon.head.female.sprite'''
Address = 0x124398
Format = '''`ucs4x2x2|graphics.townmap.icon.head.female.palette`'''

#################################
#################################
[[MatchedWords]]
Name = '''scripts.daycare.exp.multiplier'''
Address = 0x070AE8
Length = 1
Note = '''Picking an even number will prevent new eggs from being created.'''

[[MatchedWords]]
Name = '''scripts.newgame.money'''
Address = 0x0845BC
Length = 2

[[MatchedWords]]
Name = '''scripts.battle.trade.exp.boost'''
Address = 0x04A6FC
Length = 1

#################################
#################################
[[List]]
Name = '''egggroups'''
0 = [
   '''None''',
   '''Monster''',
   '''Water1''',
   '''Bug''',
   '''Flying''',
   '''Field''',
   '''Fairy''',
   '''Grass''',
   '''Human-Like''',
   '''Water3''',
   '''Mineral''',
   '''Amorphous''',
   '''Water2''',
   '''Ditton''',
   '''Dragon''',
   '''Undiscovered''',
]

[[List]]
Name = '''moveeffectoptions'''
0 = [
   '''None''',
   '''SleepPrimary''',
   '''Poison''',
   '''HealHalf''',
   '''Burn''',
   '''Freeze''',
   '''Paralyze''',
   '''SelfKO''',
   '''HealHalfIfOpponentSleeping''',
   '''RepeatFoeMove''',
   '''RaiseAttackPrimary''',
   '''RaiseDefensePrimary''',
   '''???RaiseSpeedPrimary???''',
   '''RaiseSpAttackPrimary''',
   '''unknown1''',
   '''???RaiseAccuracyPrimary???''',
   '''RaiseEvasivenessPrimary''',
   '''NeverMiss''',
   '''LowerAttackPrimary''',
   '''LowerDefensePrimary''',
   '''LowerSpeedPrimary''',
   '''???LowerAttackSpAttackPrimary???''',
   '''unknown2''',
   '''LowerAccuracyPrimary''',
   '''LowerEvasionPrimary''',
   '''RemoveStateChanges''',
   '''Bide''',
   '''2to3turnsThenConfused''',
   '''OpponentSwitch''',
   '''2to5hits''',
   '''ChangeTypeToFriendlyMove''',
   '''Flinch''',
   '''Recover''',
   '''BadPoisonPrimary''',
   '''Money''',
   '''RaiseSpDef2Wall''',
   '''ParalyzeBurnFreeze''',
   '''Rest''',
   '''OHKO''',
   '''2turnHighCrit''',
   '''HalfDamage''',
   '''20Damage''',
   '''2to5turnTrap''',
   '''HighCrit''',
   '''2hits''',
   '''MissHurtSelf''',
   '''PreventStatReduction''',
   '''RaiseCriticalRate''',
   '''25Recoil''',
   '''ConfusionPrimary''',
   '''RaiseAttack2Primary''',
   '''RaiseDefense2Primary''',
   '''RaiseSpeed2Primary''',
   '''RaiseSpAtk2Primary''',
   '''RaiseSpDef2Primary''',
   '''???RaiseAccuracy2Primary???''',
   '''???RaiseEvasiveness2Primary???''',
   '''Transform''',
   '''LowerAttack2Primary''',
   '''LowerDefense2Primary''',
   '''LowerSpeed2Primary''',
   '''???LowerSpAtk2Primary???''',
   '''LowerSpDef2Primary''',
   '''???''',
   '''????''',
   '''RaiseDefense2Wall''',
   '''PoisonPrimary''',
   '''ParalyzePrimary''',
   '''LowerAttack''',
   '''LowerDefense''',
   '''LowerSpeed''',
   '''LowerSpAtk''',
   '''LowerSpDef''',
   '''LowerAccuracy''',
   '''?????''',
   '''2turnHighCritFlinch''',
   '''Confusion''',
   '''2hitsPoison''',
   '''NeverMiss(VitalThrow)''',
   '''Substitute''',
   '''SkipNextTurn''',
   '''StrongerForLessHealth''',
   '''Mimic''',
   '''RandomMove''',
   '''SeedOpponent''',
   '''Splash''',
   '''Disable''',
   '''DamageBasedOnLevel''',
   '''DamageRandom''',
   '''DoublePhysicalDamage''',
   '''OpponentRepeatMoveFor2to6turns''',
   '''PainSplit''',
   '''WhileSleepingFlinch''',
   '''ChangeTypeToResistPreviousHit''',
   '''NextAttackHits''',
   '''Sketch''',
   '''??????''',
   '''SleepTalk''',
   '''DestinyBond''',
   '''StrengthDependsOnHealth''',
   '''ReducePP''',
   '''FalseSwipe''',
   '''HealPartyStatus''',
   '''NormalPlusPriority''',
   '''3turnTripleHit''',
   '''StealItem''',
   '''NoSwitch''',
   '''Nightmare''',
   '''RaiseEvasivenessAndBecomeSmaller''',
   '''Curse''',
   '''??''',
   '''EvadeNextAttack''',
   '''Spikes''',
   '''FoeCannnotRaiseEvasion''',
   '''PerishSong''',
   '''Sandstorm''',
   '''Endure''',
   '''5turnsUntilMiss''',
   '''ConfuseAndRaiseAttack2''',
   '''GetStrongerEachHit''',
   '''Attract''',
   '''StrongerWithFriendship''',
   '''Present''',
   '''WeakerWithFriendship''',
   '''PreventStatus5Turns''',
   '''BurnDefrost''',
   '''Magnitude''',
   '''BatonPass''',
   '''DoublePowerIfOpponentSwitching''',
   '''RemoveBindSeedSpikes''',
   '''20Damage''',
   '''???????''',
   '''MorningSun''',
   '''Synthesis''',
   '''Moonlight''',
   '''HiddenPower''',
   '''Rain5turns''',
   '''Sun5turns''',
   '''RaiseDefense''',
   '''RaiseAttack''',
   '''RaiseAllStats''',
   '''????????''',
   '''HalfHealthToRaiseAttack6''',
   '''CopyFoeStatChangesPrimary''',
   '''DoubleSpecialDamage''',
   '''RaiseDefenseThenAttackTurn2''',
   '''FlinchAndDoubleDamageToFly''',
   '''DoubleDamageToDig''',
   '''DamageIn2Turns''',
   '''DoubleDamageToFly''',
   '''FlinchAndDoubleDamageToMinimize''',
   '''ChargeFirstTurn''',
   '''ParalyzeAndIncreaseAccuracyInRain''',
   '''Escape''',
   '''DamageBasedOnPartySize''',
   '''2turn''',
   '''RaiseDefenseAndImproveRollingMoves''',
   '''RecoverOrFriend''',
   '''OnlyWorksOnce''',
   '''2to5turnsNoSleep''',
   '''Stockpile''',
   '''Spit Up''',
   '''Swallow''',
   '''?????????''',
   '''Hail5turns''',
   '''Torment''',
   '''ConfuseAndRaiseSpAtk2''',
   '''BurnPrimary''',
   '''SelfKOLowerAtkSpAtk2''',
   '''DoubleDamageIfStatus''',
   '''SelfFlinchIfHit''',
   '''DoubleDamageToParalyzeAndHealParalyze''',
   '''ForceFoesAttackMe''',
   '''NaturePower''',
   '''BoostNextElectricMove''',
   '''Taunt''',
   '''BoostAllyPower''',
   '''TradeHeldItems''',
   '''CopyAbility''',
   '''HealHalfNextTurn''',
   '''UseAllyMove''',
   '''Ingrain''',
   '''LowerSelfAtkDef''',
   '''ReflectStatusMoves''',
   '''Recycle''',
   '''DoubleDamageIfHitThisTurn''',
   '''BreakWall''',
   '''Yawn''',
   '''KnockOff''',
   '''Endeavor''',
   '''DamageBasedOnHighRemainingHealth''',
   '''SkillSwap''',
   '''Imprison''',
   '''HealSelfStatus''',
   '''Grudge''',
   '''Snatch''',
   '''DamageBasedOnWeight''',
   '''SecondEffectBasedOnTerrain''',
   '''33Recoil''',
   '''ConfuseAllPokemon''',
   '''HighCritBurn''',
   '''MudSport''',
   '''BadPoison''',
   '''WeatherBall''',
   '''LowerSpAtk2Self''',
   '''LowerAttackDefensePrimary''',
   '''RaiseDefenseSpDef''',
   '''CanDamageFly''',
   '''RaiseAttackDefensePrimary''',
   '''HighCritPoison''',
   '''WaterSport''',
   '''RaiseSpAtkSpDefPrimary''',
   '''RaiseAttackSpeedPrimary''',
   '''ChangetypeFromTerrain''',
]

[[List]]
Name = '''moveinfo'''
0 = [
   '''Makes Contact''',
   '''Affected by Protect''',
   '''Affected by Magic Coat''',
   '''Affected by Snatch''',
   '''Affected by Mirror Move''',
   '''Affected by King's Rock''',
]

[[List]]
Name = '''holdeffects'''
0 = [
   '''None''',
   '''Heal|HP Yellow|Once''',
   '''Remove Paralysis|Once''',
   '''Remove Sleep|Once''',
   '''Remove Poison|Once''',
   '''Remove Burn|Once''',
   '''Remove Freeze|Once''',
   '''Restore PP|Empty|Once''',
   '''Remove Confusion|Once''',
   '''Remove Any Status Condition|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Boost ATK|HP Red|Once''',
   '''Boost DEF|HP Red|Once''',
   '''Boost SPD|HP Red|Once''',
   '''Boost SP.ATK|HP Red|Once''',
   '''Boost SP.DEF|HP Red|Once''',
   '''Boost Crit.Ratio|HP Red|Once''',
   '''Sharp Boost Random Stat|HP Red|Once''',
   '''Reduce Enemy Accuracy''',
   '''Restore Any Stat Loss|Once''',
   '''Macho Brace''',
   '''Exp. Share''',
   '''May Strike First''',
   '''Boost Friendliness''',
   '''Remove Infatuation''',
   '''Choice Band''',
   '''Enemy May Flinch''',
   '''Boost Bug-Type Moves''',
   '''Doubles Battle Money''',
   '''Repels Wild PKMN''',
   '''Soul Dew''',
   '''Boost SP.ATK''',
   '''Boost SP.DEF''',
   '''Flee Any Wild Battle''',
   '''Prevent Evolution''',
   '''May Endure Hit''',
   '''Boost Exp. Gain''',
   '''Boost Crit Ratio''',
   '''Boost Steel-Type Moves''',
   '''Restore Health Each Round''',
   '''No effect''',
   '''Boost SP.ATK For Pikachu''',
   '''Boost Ground-Type Moves''',
   '''Boost Rock-Type Moves''',
   '''Boost Grass-Type Moves''',
   '''Boost Dark-Type Moves''',
   '''Boost Fighting-Type Moves''',
   '''Boost Electric-Type Moves''',
   '''Boost Water-Type Moves''',
   '''Boost Flying-Type Moves''',
   '''Boost Poison-Type Moves''',
   '''Boost Ice-Type Moves''',
   '''Boost Ghost-Type Moves''',
   '''Boost Psychic-Type Moves''',
   '''Boost Fire-Type Moves''',
   '''Boost Dragon-Type Moves''',
   '''Boost Normal-Type Moves''',
   '''Up-Grade''',
   '''Heal When Striking An Enemy''',
   '''Boost Chansey's Crit.Ratio''',
   '''Boost Ditto's DEF''',
   '''Boost Cubone and Marowak ATK''',
   '''Boost Farfetch'd Crit.Ratio''',
]

[[List]]
Name = '''contestPokemonFlags'''
0 = [
   '''whichRankHigh''',
   '''whichRankLow''',
   '''Cool''',
   '''Beauty''',
   '''Cute''',
   '''Smart''',
   '''Tough''',
]

[[List]]
Name = '''owfootprints'''
0 = [
   '''None''',
   '''Feet''',
   '''Bike''',
]

[[List]]
Name = '''movetarget'''
0 = [
   '''RecentAttacker''',
   '''UserOrSelected''',
   '''Random''',
   '''Both''',
   '''Self''',
   '''Everyone''',
   '''Hazard''',
]

[[List]]
Name = '''trainerStructType'''
0 = [
   '''Normal''',
   '''Moves''',
   '''Items''',
   '''Both''',
]

[[List]]
Name = '''decorpermissions'''
0 = [
   '''Normal''',
   '''Put On Floor''',
   '''Object''',
   '''Place On Wall''',
   '''Doll or Cushion''',
]

[[List]]
Name = '''decorcategory'''
0 = [
   '''Desk''',
   '''Chair''',
   '''Plant''',
   '''Unique''',
   '''Mat''',
   '''Poster''',
   '''Doll''',
   '''Cushion''',
]

[[List]]
Name = '''decorshape'''
0 = [
   '''1x1''',
   '''2x1''',
   '''unused''',
   '''1x1t''',
   '''2x2p''',
   '''1x1p''',
   '''unused''',
   '''3x1''',
   '''2x2''',
   '''3x2''',
]

[[List]]
Name = '''evolutionmethods'''
0 = [
   '''None''',
   '''Happiness''',
   '''Happy Day''',
   '''Happy Night''',
   '''Level''',
   '''Trade''',
   '''Trade Item''',
   '''Stone''',
   '''Level High Attack''',
   '''Level Attack matches Defense''',
   '''Level High Defense''',
   '''Level Odd Personality''',
   '''Level Even Personality''',
   '''Level And New Pokemon''',
   '''Level But New Pokemon''',
   '''Beauty''',
]

[[List]]
Name = '''evbits'''
0 = [
   '''+1 HP''',
   '''+2 HP''',
   '''+1 Attack''',
   '''+2 Attack''',
   '''+1 Defense''',
   '''+2 Defense''',
   '''+1 Speed''',
   '''+2 Speed''',
   '''+1 Sp Attack''',
   '''+2 Sp Attack''',
   '''+1 Sp Defense''',
   '''+2 Sp Defense''',
]

[[List]]
Name = '''battletowerEvFlags'''
0 = [
   '''Hp''',
   '''Attack''',
   '''Defense''',
   '''Speed''',
   '''SpAttack''',
   '''SpDefense''',
]

[[List]]
Name = '''traineraibits'''
0 = [
   '''CheckBadMove''',
   '''TryToFaint''',
   '''CheckViability''',
   '''SetupFirstTurn''',
   '''Risky''',
   '''PreferStrongestMove''',
   '''PreferBatonPass''',
   '''DoubleBattle''',
   '''HPAware''',
   '''Unknown''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Roaming''',
   '''Safari''',
   '''FirstBattle''',
]

[[List]]
Name = '''script_compare'''
0 = [
   '''<''',
   '''=''',
   '''>''',
   '''<=''',
   '''>=''',
   '''!=''',
]

[[List]]
Name = '''catchmap_shape'''
0 = [
   '''small''',
   '''wide''',
   '''tall''',
   '''wider''',
   '''taller''',
   '''widest''',
   '''tallest''',
]

[[List]]
Name = '''movementtypes'''
0 = [
   '''face_down''',
   '''face_up''',
   '''face_left''',
   '''face_right''',
   '''walk_slow_down''',
   '''walk_slow_up''',
   '''walk_slow_left''',
   '''walk_slow_right''',
   '''walk_down''',
   '''walk_up''',
   '''walk_left''',
   '''walk_right''',
   '''jump_2_down''',
   '''jump_2_up''',
   '''jump_2_left''',
   '''jump_2_right''',
   '''delay_1''',
   '''delay_2''',
   '''delay_4''',
   '''delay_8''',
   '''delay_16''',
   '''walk_fast_down''',
   '''walk_fast_up''',
   '''walk_fast_left''',
   '''walk_fast_right''',
   '''walk_in_place_slow_down''',
   '''walk_in_place_slow_up''',
   '''walk_in_place_slow_left''',
   '''walk_in_place_slow_right''',
   '''walk_in_place_down''',
   '''walk_in_place_up''',
   '''walk_in_place_left''',
   '''walk_in_place_right''',
   '''walk_in_place_fast_down''',
   '''walk_in_place_fast_up''',
   '''walk_in_place_fast_left''',
   '''walk_in_place_fast_right''',
   '''walk_in_place_fastest_down''',
   '''walk_in_place_fastest_up''',
   '''walk_in_place_fastest_left''',
   '''walk_in_place_fastest_right''',
   '''ride_water_current_down''',
   '''ride_water_current_up''',
   '''ride_water_current_left''',
   '''ride_water_current_right''',
   '''walk_fastest_down''',
   '''walk_fastest_up''',
   '''walk_fastest_left''',
   '''walk_fastest_right''',
   '''slide_down''',
   '''slide_up''',
   '''slide_left''',
   '''slide_right''',
   '''player_run_down''',
   '''player_run_up''',
   '''player_run_left''',
   '''player_run_right''',
   '''start_anim_in_direction''',
   '''jump_special_down''',
   '''jump_special_up''',
   '''jump_special_left''',
   '''jump_special_right''',
   '''face_player''',
   '''face_away_player''',
   '''lock_facing_direction''',
   '''unlock_facing_direction''',
   '''jump_down''',
   '''jump_up''',
   '''jump_left''',
   '''jump_right''',
   '''jump_in_place_down''',
   '''jump_in_place_up''',
   '''jump_in_place_left''',
   '''jump_in_place_right''',
   '''jump_in_place_down_up''',
   '''jump_in_place_up_down''',
   '''jump_in_place_left_right''',
   '''jump_in_place_right_left''',
   '''face_original_direction''',
   '''nurse_joy_bow''',
   '''enable_jump_landing_ground_effect''',
   '''disable_jump_landing_ground_effect''',
   '''disable_anim''',
   '''restore_anim''',
   '''set_invisible''',
   '''set_visible''',
   '''emote_exclamation_mark''',
   '''emote_question_mark''',
   '''emote_heart''',
   '''reveal_trainer''',
   '''rock_smash_break''',
   '''cut_tree''',
   '''set_fixed_priority''',
   '''clear_fixed_priority''',
   '''init_affine_anim''',
   '''clear_affine_anim''',
   '''hide_reflection''',
   '''show_reflection''',
   '''walk_down_start_affine''',
   '''walk_down_affine''',
]
140 = [
   '''walk_diag_northwest''',
   '''walk_diag_northeast''',
   '''walk_diag_southwest''',
   '''walk_diag_southeast''',
   '''walk_slow_diag_northwest''',
   '''walk_slow_diag_northeast''',
   '''walk_slow_diag_southwest''',
   '''walk_slow_diag_southeast''',
   '''store_lock_anim''',
   '''free_unlock_anim''',
   '''walk_left_affine''',
   '''walk_right_affine''',
   '''levitate''',
   '''stop_levitate''',
   '''destroy_extra_task''',
   '''figure_8''',
   '''fly_up''',
   '''fly_down''',
]

