gText_Birch_Welcome:: @ 82C897B
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"





@OFFICIAL MINIGAME INVESTIGATOR CONTENT AHEAD
gText_PlayerNameIs::
	.string "This diary belongs to..."
	.string "$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Choose your appearence.\n"
	.string "$"

gText_PlayerConfirmed::
	.string "This diary belongs to {PLAYER}."
	.string "$"

gText_DearDiary::
	.string "Dear diary,\p"
	.string "I'm back in Hurricane, Utah.\p"
	.string "$"

gText_WhoWould::
	.string "Who would have thought\n"
	.string "that, after so many years,\l"
	.string "I'd come back here?\p"
	.string "$"

gText_TheyWould::
	.string "...well, my parents\p"
	.string "certainly did."
	.string"$"

gText_Everyone::
	.string "And so did everyone else,\n"
	.string "apparently.\p"
	.string "This is supposedly a town\n"
	.string "where everyone seems to \l"
	.string "come back to, but the population\l"
	.string "rarely grows."
	.string"$"

gText_Creepy::
	.string "Whether that's creepy, or just\n"
	.string "self-fulfilling prophecy,\l"
	.string "I cannot tell."
	.string"$"

gText_BackHome::
	.string "Anyway,\n"
	.string "I'm back home."
	.string"$"
