	.align 2
gText_ConfirmSave:: @ 82C87B4
	.string "Wanna save?$"

gText_AlreadySavedFile:: @ 82C87D5
	.string "Is it okay to overwrite the\n"
	.string "last save?$"

gText_SavingDontTurnOff::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedGame::
	.string "{PLAYER} saved the game.$"

gText_DifferentSaveFile:: @ 82C8845
	.string "WAIT UP!\p"
	.string "There's already a save file!\p"
	.string "If you delete it,\n"
	.string "all progress, including unlocked\l"
	.string "minigames, children's souls\l"
	.string "and other unlocks will be reset!\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Use your emulator's\n"
	.string "save state instead.$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"
